apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: barista-kafka
  labels:
    deploymentName: barista-kafka
spec:
  scaleTargetRef:
    deploymentName: barista-kafka
  pollingInterval: 1
  cooldownPeriod:  300
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: kafka
      metadata:
        topic: orders
        brokerList: {{ .Values.kafka.bootstrap.service }}.{{ .Values.kafka.namespace }}:{{ .Values.kafka.bootstrap.port }}
        consumerGroup: baristas
        lagThreshold: '3'