kind: Route
apiVersion: v1
metadata:
  name: coffee-shop
  namespace: coffee
spec:
  to:
    kind: Service
    name: coffee-shop
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect